{{- if not $.Values.openshift }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: solace-exporter-proxy
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
spec:
  ingressClassName: nginx-example
  rules:
  - host: "{{ $.Values.exporter_proxy.hostname }}" 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: solace-exporter-proxy
            port:
              number: 9000
{{ end }}