on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        default: '1.0.0-dev'

jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Whitesource Action
        uses: mercari/Whitesource-Scan-Action@v1.0.0
        with:
          wssURL: https://saas.whitesourcesoftware.com/agent
          apiKey: ${{ secrets.WSS_API_KEY }}
          productName: 'pubsubplus-prometheus-exporter'
          projectName: 'pubsubplus-prometheus-exporter'
          configFile: 'ci/whitesource/whitesource-agent.config'


      - name: Generate Third Party License
        run: |
          make generate-license

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v12
        id: verify-changed-files
        with:
          files: THIRD-PARTY-LICENSES.md

      - name: Commit changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add THIRD-PARTY-LICENSES.md
          git commit -m "chore: Updated third party license."

      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.ref }}

      - name: Build
        run: make build

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            ghcr.io/solacedev/pubsubplus_prometheus_exporter:${{ github.event.inputs.release_tag }}
          #push: ${{ github.ref == 'refs/heads/1.0.0' }}
          push: true

      - name: Test image
        run: |
          pushd /tmp
          curl -s https://api.github.com/repos/redhat-openshift-ecosystem/openshift-preflight/releases/latest | grep -wo "https://.*preflight-linux-amd64" | wget -i -
          chmod +x preflight-linux-amd64
          popd
          export VERSION='${{ github.event.inputs.release_tag }}'
          export CONTAINER_TO_TEST="ghcr.io/solacedev/pubsubplus_prometheus_exporter:$VERSION"
          echo "Testing $CONTAINER_TO_TEST"
          /tmp/preflight-linux-amd64 check container $CONTAINER_TO_TEST --docker-config ~/.docker/config.json | grep "Preflight result: PASSED" || echo

      - name: Build and publish
        run: |
          export VERSION='${{ github.event.inputs.release_tag }}'
          # tag as latest
          PUSHED_IMAGES=`docker images | grep $VERSION`
          EXPORTER=`echo "$PUSHED_IMAGES" | grep prometheus` ; echo "$EXPORTER"   # Format: Imagepath Tag Sha
          docker tag `echo $EXPORTER | awk '{print $3}'` `echo $EXPORTER | awk '{print $1}'`:latest
          docker push `echo $EXPORTER | awk '{print $1}'`:latest
