on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        default: '1.0.0-dev'

jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Whitesource Action
        uses: mercari/Whitesource-Scan-Action@v1.0.0
        with:
          wssURL: https://saas.whitesourcesoftware.com/agent
          apiKey: ${{ secrets.WSS_API_KEY }}
          productName: 'pubsubplus-prometheus-exporter'
          projectName: 'pubsubplus-prometheus-exporter'
          configFile: 'ci/whitesource/whitesource-agent.config'

      - name: Generate Third Party License
        run: |
          make generate-license

      - name: Build exporter
        run: make build

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            ghcr.io/solacedev/pubsubplus-prometheus-exporter:${{ github.event.inputs.release_tag }}
          push: true

      - name: Test image
        run: |
          pushd /tmp
          curl -s https://api.github.com/repos/redhat-openshift-ecosystem/openshift-preflight/releases/latest | grep -wo "https://.*preflight-linux-amd64" | wget -i -
          chmod +x preflight-linux-amd64
          popd
          export VERSION='${{ github.event.inputs.release_tag }}'
          export CONTAINER_TO_TEST="ghcr.io/solacedev/pubsubplus-prometheus-exporter:$VERSION"
          echo "Testing $CONTAINER_TO_TEST"
          /tmp/preflight-linux-amd64 check container $CONTAINER_TO_TEST --docker-config ~/.docker/config.json | grep "Preflight result: PASSED" || echo

      - name: Tag same image as latest and push
        run: |
          export VERSION='${{ github.event.inputs.release_tag }}'
          # tag as latest
          PUSHED_IMAGES=`docker images | grep $VERSION`
          EXPORTER=`echo "$PUSHED_IMAGES" | grep prometheus` ; echo "$EXPORTER"   # Format: Imagepath Tag Sha
          docker tag `echo $EXPORTER | awk '{print $3}'` `echo $EXPORTER | awk '{print $1}'`:latest1
          docker push `echo $EXPORTER | awk '{print $1}'`:latest1

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: 'Updated licenses [skip ci]'
          add: 'THIRD-PARTY-LICENSES.md'
          new_branch: 'ReleaseCandidate-${{ github.event.inputs.release_tag }}'

      - name: Create pull request
        run: |
          CURRENT_BRANCH=${GITHUB_REF##*/}
          gh pr create -B ${CURRENT_BRANCH} -H 'ReleaseCandidate-${{ github.event.inputs.release_tag }}' --title "Merge release prep updates into ${CURRENT_BRANCH}" --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
